### PR TITLE
Update to 2.9.14

### PR DESCRIPTION
**Pull request by mxwi**
# Proposed Changes

> (Describe the changes and rationale behind them)

## Related Issues

> ([Github link][autolink-references] to related issues or pull requests)

[autolink-references]: https://help.github.com/articles/autolinked-references-and-urls/

### CODE REVIEW

**Comment by frenck** [comment]
So, how did you test this? And how did it work?

**Comment by Kewlmaaan** [comment]
I would also like to have the version bumped to v. 2.9.14 as this version supports the DNS challenge provider I would need
Can you tell me how to test this?
Thank you!

**Comment by zsiti** [comment]
+1 I was also looking for a way to update the jc21/nginx-proxy-manager version to the current latest (v2.9.14), similarly bumping the version number in the URL as @mxwi did - but I could not test the outcome, because when I tried to add the forked repo in Home Assistant OS's Add-on repositories, it said that's invalid. @frenck I'd gladly test this in my environment if you could point me in a direction how to test this. (Maybe I need to remove the "original" Home Assistant Community Add-ons repo, and add the forked one instead?). Thank you :)

**Comment by frenck** [comment]
Please keep comments on PR to be actual reviews. Thanks 👍

**Comment by brokenmass** [comment]
@frenck why can this PR not be merged ? 
It's just a minor update of the upstream package and solves multiple relevant bugs (like cloudfare based certificates not being renewed)
The upstream package is already tested before being published

**Comment by MartinKuhl** [comment]
any updates here?

**Comment by frenck** [comment]
No response from author, closing this PR.

**Comment by frenck** [comment]
No response from author, closing this PR.

**Pull request closed without merging**
