### PR TITLE
⬆️ Upgrades NGINX Proxy Manager to v2.2.2 and adds option to disable IPv6

### LINKED ISSUE #79: Error starting
# Problem/Motivation
When I start the add-on after migrating to version 5.0 it does'n start and the following error appear in the log:

nginx: [emerg] socket() [::]:80 failed (97: Address family not supported by protocol)
2020/03/01 22:56:47 [emerg] 15878#15878: socket() [::]:80 failed (97: Address family not supported by protocol)
[22:56:48] INFO: Starting NGinx...

### PR DESCRIPTION
**Pull request by schliflo**
# Proposed Changes

Upgrades NGINX Proxy Manager to v2.2.2, which supports disabling IPv6 via ENV: https://nginxproxymanager.com/advanced-config/#disabling-ipv6

fixes #79

Note: I am not familiar with building hassio addons, but as far as I can see, this should add a user facing option to disable IPv6 which is on by default.

<blockquote><div><strong><a href="https://nginxproxymanager.com/">Nginx Proxy Manager</a></strong></div><div>Docker container and built in Web Application for managing Nginx proxy hosts with a simple, powerful interface, providing free SSL support via Let's Encrypt</div></blockquote>

### CODE REVIEW

**Comment by frenck** [comment]
The Home Assistant system currently doesn't support IPv6, so it can be disabled by default.

The upgrade itself is already done on the master branch.

I'll patch up the master branch to disable it standard.

Thanks! 👍

**Comment by jamesking420** [comment]
Hi,

Sorry to bother you but I wondered when we would see this change in the live version of the add-on?

**Comment by frenck** [comment]
when it is ready, tested and done.

**Comment by schliflo** [comment]
@frenck how does one test the new version? It's been 20 days since the patch landed and so far the new version is not in the beta nor the edge repo.
I couldn't find documentation on how new releases are handled or the testing workflow. I'd be happy to test and provide feedback. Since this addon is broken in it's current state I'd appreciate if there'd be some progress or updated info.
Thank you for understanding :)

**Comment by frenck** [comment]
The add-on is not in a broken state, stable repo is distributed as a Docker image. It will get an update on the next release cycle, which is usually a month (unless there is a high reason to do it sooner, which there currently isn't one).

**Pull request closed without merging**
