### PR TITLE
adding trusted http integration to docs

### PR DESCRIPTION
**Pull request by Icexist**
# Proposed Changes

> Add section to documentation to clarify adding trusted proxies to Home Assistant config to prevent errors.

## Related Issues

Issue #232

### CODE REVIEW

**Comment by sinclairpaul** [comment]
This is already documented on the HTTP integration for Home Assistant, if we really want to add it, wouldn't it be better to link to that rather than duplicating docs?

**Comment by Icexist** [comment]
It is documented in the main HA docs, but it isn't clear that you must use this (or similar) config to enable a reverse proxy. With 2021.7, not having this config set will block all requests.

I thought it would be better to put all the config in one location so that users see all steps needed to enable the addon are together. I expect that without this in the documentation, users will no longer be able to access their instance and will come back to their reverse proxy to figure out what's going on. Hopefully changing the documentation during the deprecation warning (added in HA 2021.6) will minimize the amount of confusion.

**Comment by sinclairpaul** [comment]
Sure, but there is no requirement for the addon to proxy HA itself, the challenge is always in duplicating, when something changes, how does it get updated?  In my opinion the one location should be the application documentation that you are proxying to.

**Comment by Icexist** [comment]
Coming from the perspective of a user, I read through the documentation as a list of tasks to complete. So Installation instructions -> HA Configuration etc. Without a section describing this I'll expect to be done with my configuration without enabling the options in HA. I had to find this config (and that I need to use it) on forums/reddit. I'd prefer to see it in official docs.

Would it be better to have a note in the HA HTTP integration page that clarifies that you'll need this config if you use a reverse proxy? And then link from the addon docs directly to that note?

While there is no _requirement_ to proxy HA, I would expect that most people are using it for that purpose.

**Comment by frenck** [comment]
I don't want to collect "how to configure application X". That is up to the application being revered proxied to be documented.

**Pull request closed without merging**
