### PR TITLE
Update Nginx Proxy Manager to latest version

### PR DESCRIPTION
**Pull request by andrewstech**
# Proposed Changes

Update to latest version to allow use of new features.

## Related Issues

None

[autolink-references]: https://help.github.com/articles/autolinked-references-and-urls/

### CODE REVIEW

**Comment by frenck** [comment]
So, how did it work?

**Comment by andrewstech** [comment]
I manged to build the image using docker on my own system and it worked very well. But for some odd reason your GitHub actions actions script gives me an resource error when it try's to build it.

**Comment by frenck** [comment]
The reason I ask, is that the upstream project moved away from Alpine Linux, because it doesn't work with the current release of the Nginx Proxy Manager. This add-on uses Alpine Linux.

**Comment by frenck** [comment]
?

**Pull request closed without merging**
